services:
  db:
    image: postgres:17
    container_name: my-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fitness_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
